########### GET USER BY ID #############
GET http://localhost:4000/users/A242o2380

########### GET ALL USERS #############
GET http://localhost:4000/users

########### ADD A USER #############
POST http://localhost:4000/users
Content-Type: application/json

{
    "email":"diwaniva@gmail.com",
    "userPassword":"12kdvp*^5",
    "firstName":"Diwani",
    "lastName":"Kalina",
    "streetAddress":"Kahawani Rd.",
    "city":"Mombasa",
    "country":"Kenya",
    "phone":"0734289821"
}