USE Ecommerce
GO
--##########################################################################################
-- CREATE THE TABLES
-- user
-- Products
CREATE TABLE Users
(
    userId VARCHAR(100),
    -- GENERATED BY THE SERVER
    email VARCHAR(100) UNIQUE NOT NULL,
    -- ENSURES THAT ALL VALUES IN A COLUMN ARE DIFFERENT
    -- Both the UNIQUE and PRIMARY KEY constraints provide a 
    -- guarantee for uniqueness for a column or set of columns
    userPassword VARCHAR(100),
    firstName VARCHAR(100),
    lastName VARCHAR(100),
    streetAddress VARCHAR(100),
    city VARCHAR(100),
    country VARCHAR(100),
    phone VARCHAR(100),
    -- WILL BE CONVERTED TO STRING
    isDeleted INT DEFAULT 0
)

DROP TABLE Users

--##################################
--####### VIEW Users CONTENTS ######
--##################################
SELECT *
FROM Users

INSERT INTO Users
VALUES(
        '1212o2331',
        'johndoe@gmail.com',
        '12345',
        'John',
        'Doe',
        'Nyeri Rd.',
        'Nyeri',
        'Kenya',
        '0701281916',
        0
)

INSERT INTO Users
VALUES(
        'A242o2380',
        'peterpan@gmail.com',
        '1435',
        'Peter',
        'Pan',
        'Never Rd.',
        'Neverland',
        'Utopia',
        '750-23423',
        0
)

CREATE TABLE Products
(
    productId VARCHAR(100),
    -- GENERATED BY THE SERVER
    productName VARCHAR(100),
    productImage VARCHAR(100),
    productDescription VARCHAR(100),
    price INT,
    isDeleted INT DEFAULT 0
)

--######################################
--####### VIEW Products CONTENTS ######
--#####################################
SELECT *
FROM Products

--##########################################################################################









-- Register/login
-- get all
-- get one
-- update
-- delete

-- CRUD product