USE Ecommerce
GO
--####################################################
--CREATE STORED PROCEDURE FOR INSERTING USER TO TABLE
--####################################################
CREATE OR ALTER PROCEDURE addProduct(
    @productId VARCHAR(100),            -- GENERATED BY THE SERVER
    @productName VARCHAR(100),
    @productImage VARCHAR(100),
    @productDescription VARCHAR(100),
    @price INT
)
AS
BEGIN
    INSERT INTO Products
        (
        productId,                      -- GENERATED BY THE SERVER
        productName,
        productImage,
        productDescription,
        price
        )
    VALUES(
        @productId,                     -- GENERATED BY THE SERVER
        @productName,
        @productImage,
        @productDescription,
        @price
    )
END
--########################
--EXECUTE STORED PROCEDURE
--########################
EXEC addProduct '12321', 'SVS PB16 Ultra', '/product/img', 'Ported subwoofer', '2000'
EXEC addProduct '12222', 'SVS SB16 Ultra', '/product/img', 'Sealed subwoofer', '2400'

--#####################################
--########## VIEW UPDATED TABLE########
--#####################################
SELECT * FROM Products
