USE Ecommerce
GO
--######################################################
--CREATE STORED PROCEDURE FOR UPDATING INDIVIDUAL USERS
--######################################################
CREATE OR ALTER PROCEDURE updateProduct(
    @productId VARCHAR(100),
    -- GENERATED BY THE SERVER
    @productName VARCHAR(100),
    @productImage VARCHAR(100),
    @productDescription VARCHAR(100),
    @price INT
)
AS
BEGIN
    UPDATE Products
    SET productId=@productId,                      -- GENERATED BY THE SERVER
        productName=@productName,
        productImage=@productImage,
        productDescription=@productDescription,
        price=@price
    WHERE @productId = productId AND isDeleted = 0
END
--########################
--EXECUTE STORED PROCEDURE
--########################
EXEC updateProduct '12222', 'SVS SB16 Ultra', '/product/img', 'Sealed subwoofer', '2200'

--#####################################
--########## VIEW UPDATED TABLE########
--#####################################
SELECT *
FROM Products
