USE Ecommerce
GO
--####################################################
--CREATE STORED PROCEDURE FOR INSERTING USER TO TABLE
--####################################################
CREATE OR ALTER PROCEDURE addUser(
    @userId VARCHAR(100),
    -- GENERATED BY THE SERVER
    @email VARCHAR(100),
    -- ENSURES THAT ALL VALUES IN A COLUMN ARE DIFFERENT
    -- Both the UNIQUE and PRIMARY KEY constraints provide a 
    -- guarantee for uniqueness for a column or set of columns
    @userPassword VARCHAR(100),
    @firstName VARCHAR(100),
    @lastName VARCHAR(100),
    @streetAddress VARCHAR(100),
    @city VARCHAR(100),
    @country VARCHAR(100),
    @phone VARCHAR(100)
-- WILL BE CONVERTED TO STRING
)
AS
BEGIN
    INSERT INTO Users
        (
        userId,
        email,
        userPassword,
        firstName,
        lastName,
        streetAddress,
        city,
        country,
        phone
        )
    VALUES(
        @userId,
        @email,
        @userPassword,
        @firstName,
        @lastName,
        @streetAddress,
        @city,
        @country,
        @phone
    )
END
--########################
--EXECUTE STORED PROCEDURE
--########################
EXEC addUser '12133', 'maina@gmail.com', 'pwd123', 'Derick', 'Maina', 'Kakamega-kisumu Rd.', 'Kakamega', 'Kenya', '0722847312'
