USE Ecommerce
GO
--######################################################
--CREATE STORED PROCEDURE FOR UPDATING INDIVIDUAL USERS
--######################################################
CREATE OR ALTER PROCEDURE updateUser(
    @userId VARCHAR(100),
    -- GENERATED BY THE SERVER
    @email VARCHAR(100),
    -- ENSURES THAT ALL VALUES IN A COLUMN ARE DIFFERENT
    -- Both the UNIQUE and PRIMARY KEY constraints provide a 
    -- guarantee for uniqueness for a column or set of columns
    @userPassword VARCHAR(100),
    @firstName VARCHAR(100),
    @lastName VARCHAR(100),
    @streetAddress VARCHAR(100),
    @city VARCHAR(100),
    @country VARCHAR(100),
    @phone VARCHAR(100)
-- WILL BE CONVERTED TO STRING
)
AS
BEGIN
    UPDATE Users
    SET email=@email, 
        userPassword=@userPassword,
        firstName=@firstName,
        lastName=@lastName,
        streetAddress=@streetAddress,
        city=@city,
        country=@country,
        phone=@phone
    WHERE @userId = userId AND isDeleted = 0
END
--########################
--EXECUTE STORED PROCEDURE
--########################
EXEC updateUser '12133', 'maina254@gmail.com', 'pwd123', 'Derick', 'Maina', 'Kakamega-kisumu Rd.', 'Kakamega', 'Kenya', '0722847312'